server:
#自定义端口
  port: 8100
spring:
#打印彩色日志
  output:
    ansi:
      enabled: ALWAYS
      ### 选择自定义配置
  profiles:
    active: dbcopy
#    打印日志
logging:
  level:
    com.mock.crawler.dao: debug
mybatis:
#分页配置
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:com/mock/crawler/mapper/*Mapper.xml
  type-aliases-package: com.mock.crawler.Model
#  datasource:
#   # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    readSize: 1
#    write:
#      url: jdbc:mysql://localhost:3306/cn?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: tiger
#      driver-class-name: com.mysql.jdbc.Driver
#    read1:
#      url: jdbc:mysql://localhost:3306/x_jdbc?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: tiger
#      driver-class-name: com.mysql.jdbc.Driver
#server:
#  port: 8100
#spring:
#  datasource:
#   #从库数量
#    readSize: 1
#     # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#  #主库
#    write:
#      url: jdbc:mysql://localhost:3306/cn?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: tiger
#      driver-class-name: com.mysql.jdbc.Driver
#    read1:
#      url: jdbc:mysql://localhost:3306/cn?useUnicode=true&characterEncoding=utf-8&useSSL=false
#      username: root
#      password: tiger
#      driver-class-name: com.mysql.jdbc.Driver
#  output:
#    ansi:
#      enabled: ALWAYS
##主数据源
##  datasource:
##    type: com.alibaba.druid.pool.DruidDataSource
##    url: jdbc:mysql://localhost:3306/cn?useSSL=false
##    password: tiger
##    username: root
##    driver-class-name: com.mysql.jdbc.Driver
###      连接池配置
### 初始化大小数，最小空闲数，最大活动数
##    initialSize: 5
##    minIdle: 5
##    maxActive: 20
## # 配置获取连接等待超时的时间60秒
##    maxWait: 60000
## # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
##    timeBetweenEvictionRunsMillis: 60000
## # 配置一个连接在池中最小生存的时间，单位是毫秒
##    minEvictableIdleTimeMillis: 300000
##    validationQuery: SELECT 1 FROM DUAL
##    testWhileIdle: true
##    testOnBorrow: false
##    testOnReturn: false
## # 打开PSCache，并且指定每个连接上PSCache的大小
##    poolPreparedStatements: true
##    maxPoolPreparedStatementPerConnectionSize: 20
## # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙 stat,wall,log4j
##    filters: stat,log4j
## # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
##    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
##  jackson:
##    default-property-inclusion: NON_NULL
##    org.springframework.web: INFO
## 日志打印地址
##  file: f:/jsonPrin.log
## 多数据源配置
#
#    #log4j  
##logging.level.org.springframework.web=INFO  
##logging.level.org.hibernate=ERROR  
##logging.file=test.log  